services:
  deepdeepbar-be:
    image: ghcr.io/MinJun916/deepdeepbar-be
    container_name: deepdeepbar-be
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
