services:
  deepdeepbar-api:
    build: .
    container_name: deepdeepbar-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
