"""add is_sold_out to menus

Revision ID: 05d5af6b3131
Revises: 35188685c951
Create Date: 2026-05-25 10:56:25.266062

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05d5af6b3131"
down_revision: Union[str, Sequence[str], None] = "35188685c951"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menus",
        sa.Column(
            "is_sold_out", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menus", "is_sold_out")
    # ### end Alembic commands ###
