"""add menu_price model

Revision ID: a7cddcf60276
Revises: ca777fb13d5c
Create Date: 2026-05-22 02:30:05.404836

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7cddcf60276"
down_revision: Union[str, Sequence[str], None] = "ca777fb13d5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_prices",
        sa.Column("menu_id", sa.UUID(), nullable=False),
        sa.Column(
            "price_type",
            sa.Enum("bottle", "shot", "default", name="pricetypeenum"),
            nullable=False,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["menu_id"], ["menus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("menu_id"),
        sa.UniqueConstraint("price_type"),
    )
    op.add_column("menus", sa.Column("is_display", sa.Boolean(), nullable=False))

    op.drop_column("menus", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menus", sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False)
    )

    op.drop_column("menus", "is_display")
    op.drop_table("menu_prices")
    # ### end Alembic commands ###
