"""fix_menu_price_model_uniqe_policy

Revision ID: cca48dfebc0f
Revises: 8eaa6039d8ea
Create Date: 2026-05-22 03:06:52.068931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca48dfebc0f'
down_revision: Union[str, Sequence[str], None] = '8eaa6039d8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('menu_prices_menu_id_key'), 'menu_prices', type_='unique')
    op.drop_constraint(op.f('menu_prices_price_type_key'), 'menu_prices', type_='unique')
    op.create_unique_constraint('uq_menu_prices_menu_id_price_type', 'menu_prices', ['menu_id', 'price_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_menu_prices_menu_id_price_type', 'menu_prices', type_='unique')
    op.create_unique_constraint(op.f('menu_prices_price_type_key'), 'menu_prices', ['price_type'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('menu_prices_menu_id_key'), 'menu_prices', ['menu_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
